name: Expo Build iOS
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build iOS
    runs-on: ubuntu-latest
    # set the env for expo build
    env:
      EXPO_APPLE_PASSWORD: ${{ secrets.EXPO_APPLE_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
      - run: |
          npm install
          expo fetch:ios:certs
          expo bi -t archive --no-wait --team-id ${{ secrets.APPLE_TEAM_ID }} --dist-p12-path unity-mobile-dashboard_dist.p12 --provisioning-profile-path unity-mobile-dashboard.mobileprovision
