name: Expo Build iOS
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build iOS
    runs-on: macos-latest
    # set the env for expo build
    env:
      EXPO_IOS_DIST_P12_PASSWORD: ${{ secrets.EXPO_IOS_DIST_P12_PASSWORD }}
      EXPO_USERNAME: ${{ secrets.EXPO_CLI_USERNAME }}
      EXPO_PASSWORD: ${{ secrets.EXPO_CLI_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
      - run: npm install
      - run: npm install -g turtle-cli
      - run: expo fetch:ios:certs
      - name: Build ipa
        run: ipa_path = "$(turtle build:ios --team-id ${{ secrets.APPLE_TEAM_ID }} --dist-p12-path unity-mobile-dashboard_dist.p12 --provisioning-profile-path unity-mobile-dashboard.mobileprovision)"
      - name: Upload to App Store Connect
        run: xcrun altool --upload-app -f "$ipa_path" -u ${{ secrets.EXPO_APPLE_ID }} -p ${{ secrets.APP_SPECIFIC_PASSWORD }}
